### ISSUE TITLE
Add the ability to provide a default message

### ISSUE THREAD

**Issue by KieronWiltshire** [BlackyPaw/I18N#3]
Is it possible to check if the injection failed,
for example:

I want to be able to check if the injection failed to find the message, if so then display a default.
Could you allow the creation of something like:

```
Localizer#inject(key, defaultMessage);
```

**Comment by cieldeville** [comment]
Dear Kieron,

well, that depends on the error that is occuring internally. For example, if there simply is no translation of a specific key in one language but that specific key is still available in the fallback language set inside I18N's configuration it will default back to the fallback translation if instructed to do so (see the Configuration Guide). If no translation is available in the fallback language either, the localization will fail with "ENOTRANS". If you should thus ever encounter an "ENOTRANS" message you should rather interpret it as a hint to an incomplete fallback translation which is why I do not really think a default message is generally needed. Providing such a default message inside the plugin's code would break up the clear distinction between displayed text and code that I18N is striving to achieve.

In case I should have misunderstood you, feel free to comment again so that I may rework my answer.

Best regards,
BlackyPaw.

**Comment by KieronWiltshire** [comment]
Yeah, okay that's all good, I understand.
